site_name: SQL Alchemy 2.0 Russian
version: 0.0.1
repo_url: https://github.com/el1sha-git/sqlalchemy-rusdocs
repo_name: el1sha-git/sqlalchemy-rusdocs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
    - content.action.edit
#    - content.action.view
    - header.autohide
  icon:
    edit: material/pencil
    view: material/eye

  palette:
#    scheme: slate
#    primary: pink
#    accent: red

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
plugins:
  - search:
      lang:
        - ru
        - en
  - glightbox

nav:
- index.md
- Унифицированное руководство SQLAlchemy:
    - tutorial/index.md
    - tutorial/engine.md
    - tutorial/db_api.md
    - tutorial/metadata.md
    - Работа с Данными:
      - tutorial/data/index.md
      - tutorial/data/data_insert.md
      - tutorial/data/data_select.md
      - tutorial/data/data_update.md
    - tutorial/orm_data_manipulation.md
    - tutorial/orm_related_objects.md
- ORM:
    - orm/index.md
- SQLAlchemy Core:
    - core/index.md
- Диалекты:
    - dialects/index.md
- Глоссарий:
    - glossary/index.md

copyright: Copyright &copy; 2023 Elisha Kravchuk

extra:
  analytics:
    provider: google
    property: G-96L8NNF9FG
